spring.application.name=MiniCloud
spring.datasource.url=jdbc:postgresql://localhost:5432/MiniCloud
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
jwt.secret=MiniCloudSuperSecretKeyForJWTAuthentication123456789
jwt.expiration=900000  
#15 minute expiration 